### PR TITLE
Update Ecommerce events trigger to include the newer Enhanced Ecommerce events

### PR DESCRIPTION
**Pull request by KZeni**
This is updated per https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking

I kept the old event names so this should support both classic & enhanced e-commerce tracking.

### CODE REVIEW

**Comment by KZeni** [comment]
Btw, I'm thinking the JSON file can be renamed to be more appropriate as a general resource, and I've included that as part of this PR.

**Comment by KZeni** [comment]
As an aside, I contacted the GTM4WP developer (https://github.com/duracelltomi/gtm4wp) to see if this could be more formally recommended by the plugin as a way to get started quickly & easily.

**Review by zjuul — APPROVED** [review]
Thanks for the additions!

**Comment by KZeni** [comment]
Oh, I also reached out to https://gist.github.com/ju1/5f886f645d3dad38b217be2bc8001e77/ per a Google search to help unify the efforts of having a prebuilt container which takes advantage of everything GTM4WP offers (which shouldn't need to diverge in any way & therefore should have one resource that's kept up-to-date [I'm thinking yours would be best since a gist isn't as readily updatable/manageable/etc.)

**Pull request merged**
